version: '3'

services:
  llama-api:
    build:
      context: ./llama-api-docker
      dockerfile: Dockerfile
    container_name: llama-api
    ports:
      - "8000:8000"
    environment:
      - MODEL_DIR=/app/models_new/Llama-3.2-1B_new
      - PORT=8000
    volumes:
      - ./llama-api-docker/models_new:/app/models_new
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 60s

  inference-ui:
    build:
      context: ./inference-ui
      dockerfile: Dockerfile
    container_name: inference-ui
    ports:
      - "3000:3000"
    environment:
      - LLAMA_API_URL=http://llama-api:8000
      - PORT=3000
    depends_on:
      llama-api:
        condition: service_healthy 