version: '3'
services:
  llama-api:
    build: 
      context: ./llama-api-docker
      dockerfile: Dockerfile
    volumes:
      - ./llama-api-docker/models:/app/models
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/models/Llama-3.2-3B-Instruct-Q4_K_M.gguf

  inference-ui:
    build:
      context: ./inference-ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - LLAMA_API_URL=http://llama-api:8000
    depends_on:
      - llama-api
