version: '3'
services:
  llama-api:
    build: 
      context: ./llama-api-docker
      dockerfile: Dockerfile
    container_name: llama-api
    volumes:
      - ./llama-api-docker/models:/app/models
    ports:
      - "8000:8000"
    environment:
      - MODEL_PATH=/app/models/Llama-3.2-3B-Instruct-Q4_K_M.gguf
    networks:
      - app-network

  guardrails:
    build:
      context: ./guardrails
      dockerfile: Dockerfile
    container_name: guardrails
    ports:
      - "8001:8000"
    volumes:
      - ./rails:/app/rails
    networks:
      - app-network

  inference-ui:
    build:
      context: ./inference-ui
      dockerfile: Dockerfile
    container_name: inference-ui
    ports:
      - "3000:3000"
    environment:
      - LLAMA_API_URL=http://llama-api:8000
    volumes:
      - ./rails:/app/rails
    depends_on:
      - llama-api
      - guardrails
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
