models:
 - type: main
   engine: openai
   model: llama
   parameters:
     openai_api_base: http://localhost:8000
     openai_api_key: not-needed
     model_kwargs:
       api_base: http://localhost:8000
       use_completion_api: true

